### ISSUE TITLE
[BUG]: No way to add PDF Instructions (large file)

### ISSUE THREAD

**Issue by alv67** [B-AROL-O/ARNEIS#232]
### Description of the bug

Do we want to enable LFS just for some files as the Build Instructions?

### Steps To Reproduce

Add a large file > 25Mb

**Comment by gmacario** [comment]
@alv67 

> Do we want to enable LFS just for some files as the Build Instructions?

Couldn't we use MS Azure storage service instead?

Please see https://github.com/B-AROL-O/ARNEIS/issues/171

**Comment by gmacario** [comment]
Additional, I would tend to NOT commit the .PDF in the source repository, since if I am not mistaken the PDF can be generated out of the *.io file. 

Is my understanding correct?

If so, it would probably be more appropriate to update https://github.com/B-AROL-O/ARNEIS/blob/main/mocs/project/README.md (or even better, create another HOWTO) to document how the PDF can be generated, and maybe provide a link to a generated artifact, such as the one I just uploaded to MS Azure Storage Service.

**Comment by alv67** [comment]
Double-checked on the [Bricklink Studio Forum](https://forum.bricklink.com/index.php?sid=8aa9fe8d61bd8e42b6b1b299c670cb8c) and not found a way to create a PDF via something different of _Exporting_ inside the application.
As for the HOWTO, if is will be only concerning the creation of the PDF it will be not of a great value.
If the HOWTO will be concerning all the possibles works to create and edit the instruction, this will be a way too long and complex work that I can't do in this few spare time...
